# Generated by Django 5.1.2 on 2024-10-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_leafimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leafimage',
            name='crop_name',
            field=models.CharField(max_length=100),
        ),
    ]
